/*
 * Port_PBcfg.c
 *
 *  Created on: Aug 27, 2024
 *      Author: Mazen
 */

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
        ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
        ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
        ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
        ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The SW version of PBcfg.c does not match the expected version"
#endif





 Port_ConfigType Port_PinConfigurationSet = {
    PIN0, PORTA, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN1, PORTA, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN2, PORTA, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN3, PORTA, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN4, PORTA, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN5, PORTA, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN6, PORTA, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN7, PORTA, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,

    PIN0, PORTB, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN1, PORTB, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN2, PORTB, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN3, PORTB, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN4, PORTB, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN5, PORTB, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN6, PORTB, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN7, PORTB, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,

    PIN0, PORTC, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_NULL, PORT_PIN_MODE_NULL, STD_OFF, STD_OFF,
    PIN1, PORTC, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_NULL, PORT_PIN_MODE_NULL, STD_OFF, STD_OFF,
    PIN2, PORTC, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_NULL, PORT_PIN_MODE_NULL, STD_OFF, STD_OFF,
    PIN3, PORTC, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_NULL, PORT_PIN_MODE_NULL, STD_OFF, STD_OFF,
    PIN4, PORTC, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN5, PORTC, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN6, PORTC, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN7, PORTC, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,

    PIN0, PORTD, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN1, PORTD, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN2, PORTD, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN3, PORTD, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN4, PORTD, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN5, PORTD, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN6, PORTD, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN7, PORTD, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,

    PIN0, PORTE, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN1, PORTE, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN2, PORTE, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN3, PORTE, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN4, PORTE, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN5, PORTE, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,

    PIN0, PORTF, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN1, PORTF, OUTPUT,PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN2, PORTF, OUTPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN3, PORTF, OUTPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
    PIN4, PORTF, INPUT, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_DIO, STD_OFF, STD_OFF,
};




